Adding prometheus exporter
netboxlabs/pktvisor pull request #19
Opened 2020-11-24 11:52 UTC by tuannh99

This should add prometheus exporter for pktvisor

2020-11-24 18:10 UTC, weyrick requested changes
Thanks for this! Since there may be other exporters, can you please rename it from `pktvisor_exporter` to `pktvisor_prometheus` or similar? And then please put it under the `reporting/` directory for now, where we can start to organize tools and documentation for central collection and visibility.

2020-11-24 18:10 UTC, weyrick commented on pktvisor_exporter/pktvisor_exporter_test.go
> +// Copyright (C) 2016, 2017 Nicolas Lamirault <nicolas.lamirault@gmail.com>
assuming this is copy paste, please fix

2020-11-25 10:06 UTC, tnguyenns1 commented on pktvisor_exporter/pktvisor_exporter_test.go
> +// Copyright (C) 2016, 2017 Nicolas Lamirault <nicolas.lamirault@gmail.com>
@weyrick All fixed.

2020-11-25 10:07 UTC, tuannh99 commented on pktvisor_exporter/pktvisor_exporter_test.go
> +// Copyright (C) 2016, 2017 Nicolas Lamirault <nicolas.lamirault@gmail.com>
@weyrick All fixed.

2020-12-14 20:11 UTC, weyrick approved these changes

2020-12-14 20:15 UTC, merged