Feature/netflow ipfix support
netboxlabs/pktvisor pull request #275
Opened 2022-04-26 17:51 UTC by leoparente

2022-04-27 20:28 UTC, weyrick requested changes

2022-04-27 20:28 UTC, weyrick commented on src/inputs/flow/FlowInput.conf
> +provides=flow
can we do "providers=sflow" too?

2022-04-27 20:28 UTC, weyrick commented on src/inputs/flow/FlowInputStream.cpp
> +        throw FlowException("flow config must specify flow_type");
default to "sflow" (with a warning log) for backwards compat?

2022-04-27 20:28 UTC, weyrick commented on src/inputs/flow/FlowInputStream.cpp
> +            throw FlowException(fmt::format("invalid flow type: {}", flow_type));
let's list the ones we support here in the error message

2022-04-27 21:54 UTC, leoparente commented on src/inputs/flow/FlowInput.conf
> +provides=flow
done

2022-04-28 13:43 UTC, weyrick approved these changes

2022-04-28 14:50 UTC, merged