Add flow metric for IP address and port number together
netboxlabs/pktvisor pull request #294
Opened 2022-06-15 20:44 UTC by leoparente

2022-06-15 21:00 UTC, rboucher-ns1 approved these changes
Looks good to me.

2022-06-16 13:58 UTC, weyrick requested changes

2022-06-16 13:58 UTC, weyrick commented on src/handlers/flow/FlowStreamHandler.cpp
> +                if (flow.src_port > 0) {
dst_port

2022-06-16 13:58 UTC, weyrick commented on src/handlers/flow/FlowStreamHandler.cpp
> +                if (flow.src_port > 0) {
dst_port

2022-06-16 14:32 UTC, leoparente commented on src/handlers/flow/FlowStreamHandler.cpp
> +                if (flow.src_port > 0) {
done

2022-06-16 14:33 UTC, leoparente commented on src/handlers/flow/FlowStreamHandler.cpp
> +                if (flow.src_port > 0) {
done

2022-06-16 14:34 UTC, leoparente commented on src/handlers/flow/FlowStreamHandler.h
> +            , topSrcIPandPort("flow", "ip_port", {"top_src_ips_and_port_" + metric}, "Top source IP addresses and port by " + metric)
@weyrick  @rboucher-ns1  do you agree with this tag name "ip_port" instead of only "ip"

2022-06-16 17:48 UTC, weyrick approved these changes

2022-06-16 17:48 UTC, weyrick commented on src/handlers/flow/FlowStreamHandler.h
> +            , topSrcIPandPort("flow", "ip_port", {"top_src_ips_and_port_" + metric}, "Top source IP addresses and port by " + metric)
yes, it should definitely not just be "ip" or just "port" so i guess this is best

2022-06-16 17:52 UTC, merged