Add TopN based on Failed IPs on GeoLoc and ASN lookup
netboxlabs/pktvisor pull request #301
Opened 2022-06-17 22:58 UTC by leoparente

2022-06-19 16:22 UTC, rboucher-ns1 reviewed
Looks really good and thanks for taking this on so quickly (much appreciated!).

My main comment/concern is around using the term `error` in this context. I would rather we give the variables names that reflect the status of the lookup (like `notfound` or `lookupfailure`). My preference is for the shorter `notfound`.

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/GeoDB.cpp
> +std::string MaxmindDB::getGeoLocString(const struct sockaddr *sa, bool &error) const
instead of calling it `error`, should we call it `notfound`? it's not an actual error but rather a status/condition

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/handlers/flow/FlowStreamHandler.cpp
> +        _topGeoLocError.merge(other._topGeoLocError);
similar to previous, should we consider calling it `_topGeoLocNotFound`?

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/handlers/flow/FlowStreamHandler.cpp
> +        _topASNError.merge(other._topASNError);
`_topASNNotFound`?

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/GeoDB.cpp
> +std::string MaxmindDB::getASNString(const struct sockaddr *sa, bool &error) const
similar to previous, instead of calling it error should we call it `notfound`? it's not an actual error but rather a status/condition

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/handlers/flow/FlowStreamHandler.h
> +        , _topGeoLocError(FLOW_SCHEMA, "geo_loc", {"top_geoLoc_error"}, "Top IP addresses that failed GeoLoc lookup")
"Top IP addresses that were not found during Geo Location lookup"

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/handlers/flow/FlowStreamHandler.h
> +        , _topASNError(FLOW_SCHEMA, "asn", {"top_ASN_error"}, "Top IP addresses that failed ASN lookup")
"Top IP addresses that were not found during ASN lookup"

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/handlers/net/NetStreamHandler.h
> +        , _topGeoLocError("packets", "geo_loc", {"top_geoLoc_error"}, "Top IP addresses that failed GeoLoc lookup")
"Top IP addresses that were not found during Geo Location lookup"

2022-06-19 16:22 UTC, rboucher-ns1 commented on src/handlers/net/NetStreamHandler.h
> +        , _topASNError("packets", "asn", {"top_ASN_error"}, "Top IP addresses that failed ASN lookup")
"Top IP addresses that were not found during ASN lookup"

2022-06-19 16:58 UTC, weyrick commented
hey let's chat about this first, i think we should do this differently

2022-06-19 18:17 UTC, weyrick requested changes
agreed on calling it notfound. but i do not think this should be a new top list at all - this instead be a filter on notfound. then we get all metrics (including top ip and asn) just because we can filter on all notfounds.

2022-06-20 13:42 UTC, rboucher-ns1 commented
@weyrick The reason I suggested a metric instead of a filter was so that it would be broadly available (doesn't require a specific policy) for NS1 customers of DNS Insights. I think these metrics could have very specific value-add for NS1 customers using Filter Chains based on ASN and/or GeoLoc

2022-06-21 08:46 UTC, weyrick commented
discussed in slack here https://ns1labs.slack.com/archives/C01UNG6UK37/p1655731526294639

2022-06-23 12:27 UTC, weyrick requested changes
looks pretty good. i don't see anything that tests the filter count though? it seems to me the filter is checking != "Unknown" when it should check == so just want to make sure this has a test. 

this new LRU cache will affect the all Geo lookups, not just during filter right? i'd like to measure processing speed before and after this... this type of cache was on the optimization list anyway so nice to see it but let's prove effectiveness.

2022-06-23 12:27 UTC, weyrick commented on cmd/pktvisord/main.cpp
> +      --geo-cache N               GeoLite2 cache size for databases (default: 10000)
`GeoLite2 LRU cache size, 0 to disable. (default: 10000)`

and i'd prefer `--geo-cache-size`

2022-06-23 12:27 UTC, weyrick commented on src/GeoDB.h
> +    void enable(const std::string &database_filename, int cache_size = 10000);
let's move that number to a const somewhere

2022-06-29 19:27 UTC, leoparente commented
I've started doing some profiling using real scenario pcap data and database.

The criteria to profile were:
**1)** use pktvisor-reader with same configuration in all profiling tests
**2)** Start process and wait at least 1M packets to be processed 

The result for `develop branch` was the following:
![geo_develop](https://user-images.githubusercontent.com/23251360/176514046-277dca7d-9529-470f-9077-dc667fe9bb72.png)
We can notice that _Net Handler Call_ used **43.6%** while DNS Handler call consumed 28.3% of process CPU.

If we take a look on Net Handler Calls, MaxmindDB calls consumes **28.7%** (City + ASN)
![geo_dev_expand](https://user-images.githubusercontent.com/23251360/176514067-53f736a5-51d5-4c64-808a-d332e719fdc3.png)

2022-06-29 19:42 UTC, leoparente commented
Performed same profiling for `this branch` with `no cache`:

Testing it with cache size = 0, which will disable cache. so the expected is a similar result of develop.
![geo_without_cache](https://user-images.githubusercontent.com/23251360/176520455-237d3698-9b0f-4efc-9f96-6f77c7a2b238.png)
And the similar result occurred as expected: **43.5%**

Same for Net Handler calls. DB calls consumed **28.5%**
![geo_no_cache_expand](https://user-images.githubusercontent.com/23251360/176521422-0d237ef4-0c88-44dc-afbd-c87f04ad39c0.png)

2022-06-29 19:54 UTC, leoparente commented
Now, profiling over `this branch` with the `LRUCache enabled ` (10k sized cache)

![cache_geo](https://user-images.githubusercontent.com/23251360/176528813-3e87531a-de50-4bad-a462-18e97077bf5a.png)
Here we can see a reduction of CPU consumption on Net Handler Call. It is consuming almost the same as DNS Handler call.

Looking at DB calls, it reduced to **17.7%** (more then 10%)
![cache_expand](https://user-images.githubusercontent.com/23251360/176531945-71901410-534a-465c-a708-d2de85a2aa7b.png)

2022-06-29 20:27 UTC, rboucher-ns1 approved these changes

2022-06-29 20:27 UTC, weyrick commented
nice. can we get an idea of how many entries that took in the cache, what the hit rate is, how much memory it takes?

2022-06-29 20:58 UTC, leoparente commented
Doing some memory testing ( PS: debug build)

###  **10M Packets**

**Develop**
![memory_10M_dev](https://user-images.githubusercontent.com/23251360/176542429-33a95a9d-d74d-4374-8491-1ea999c06185.png)

**Cache GeoDB branch**
![memory_10M_cache](https://user-images.githubusercontent.com/23251360/176542678-5a3d4d77-e3ac-45ea-b970-dc2a91792609.png)

**Result:** We can see that the cache branch consumes 1MB more memory, however it takes **11 less seconds** to proccess 10M packets.

### 50M Packets

**Develop**
![memory_50M_dev](https://user-images.githubusercontent.com/23251360/176542468-d5f8cecd-4a30-4452-91a2-dd3cc5c1a217.png)

**Cache GeoDB branch**
![memory_50M_cache](https://user-images.githubusercontent.com/23251360/176543096-bc0b12d8-9659-4d12-b5e7-e05f2e69fd04.png)

**Result:** We can see that the cache branch still consumes 1MB more then develop,  however it takes **almost 1 minute** less then develop to process 50M packets

2022-06-29 21:21 UTC, weyrick approved these changes
awesomeness

2022-06-29 21:27 UTC, merged