Add NODATA count and top qname
netboxlabs/pktvisor pull request #316
Opened 2022-06-30 18:51 UTC by leoparente

2022-06-30 20:04 UTC, weyrick requested changes

2022-06-30 20:04 UTC, weyrick commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
i think we need to also ensure it's an int, as we do on line 57, otherwise 75 will fail

2022-06-30 20:13 UTC, leoparente commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
but i did the same as line 61

2022-06-30 20:20 UTC, weyrick commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
hm isn't that a bug too though? what actually happens in case the type is wrong?

2022-06-30 20:24 UTC, leoparente commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
policy apply will fail. I thought that is the expected behavior. because it the type is wrong we should throw right? Which is that we currently do

2022-06-30 20:26 UTC, leoparente commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
we also throw when rcode is not in the known range for instance

2022-06-30 20:26 UTC, weyrick commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
yes if we handle the error gracefully then that's correct - but also the error message needs to be understandable so they can know what to fix too. remember this error message will show up in the orb UI

2022-06-30 20:51 UTC, leoparente commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
Cool. I will work on that!

2022-06-30 22:16 UTC, leoparente commented on src/handlers/dns/DnsStreamHandler.cpp
> +    if (config_exists("answer_count")) {
done

2022-07-05 20:32 UTC, weyrick approved these changes

2022-07-05 21:46 UTC, merged