Implement merge_equal feature on Policies
netboxlabs/pktvisor pull request #426
Opened 2022-09-05 22:14 UTC by leoparente

2022-09-06 21:18 UTC, weyrick requested changes
Looks pretty good! Let's get some units and update to the RFC as well.

2022-09-06 21:18 UTC, weyrick commented on src/AbstractMetricsManager.h
> +            throw std::runtime_error("invalid bucket type");
this could that happen from a policy right, only programmer error?

2022-09-06 21:18 UTC, weyrick commented on src/Policies.cpp
> +    _merge_equal = (config_exists("merge_equal") && config_get<bool>("merge_equal"));
how about "merge_like_handlers" instead of "merge_equal"

2022-09-08 13:41 UTC, leoparente commented on src/AbstractMetricsManager.h
> +            throw std::runtime_error("invalid bucket type");
I've changed that to static and added a comment. It only programmer error

2022-09-08 13:42 UTC, leoparente commented on src/Policies.cpp
> +    _merge_equal = (config_exists("merge_equal") && config_get<bool>("merge_equal"));
cool. changed that

2022-09-08 16:44 UTC, weyrick approved these changes
cool let's try it!

2022-09-08 16:57 UTC, merged